[build]
  command = "npm run build"
  functions = "dist-api"
  publish = "dist-ui"

[dev]
  port = 9000

[[plugins]]
package = "netlify-plugin-contextual-env"
  [plugins.inputs]
  mode = "prefix"
[[plugins]]
package = "netlify-plugin-inline-functions-env"
  [plugins.inputs]
  verbose = "true"
  buildEvent = "onBuild"
