[build]
  command = "npm run build"
  publish = "./dist-ui"

[dev]
  publish = "./dist-ui"

[functions]
  directory = "./src/api/"
  node_bundler = "esbuild"

[[plugins]]
package = "netlify-plugin-contextual-env"
  [plugins.inputs]
  mode = "prefix"
[[plugins]]
package = "netlify-plugin-inline-functions-env"
  [plugins.inputs]
  buildEvent = "onBuild"
