[build]
  publish = "dist-ui"
  command = "npm run build"

[dev]
  targetPort = "8080"

[functions]
  directory = "./src/api/"
  node_bundler = "esbuild"

[[plugins]]
package = "netlify-plugin-contextual-env"
  [plugins.inputs]
  mode = "prefix"
[[plugins]]
package = "netlify-plugin-inline-functions-env"
  [plugins.inputs]
  buildEvent = "onBuild"
